apiVersion: v1
kind: Service
metadata:
  name: {{ include "duckdb-ui.fullname" . }}
  labels:
{{- include "duckdb-ui.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "duckdb-ui.selectorLabels" . | nindent 4 }}
